
[package]
name = "crud_api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1"
tokio-postgres = "0.7.13"
warp = "0.3.2"
serde_json = "1.0.64"
serde = "1.0.130"
serde_derive = "1.0.130"

[[bin]]
name = "crud_api"
path = "src/main.rs"
