
[package]
name = "crud_api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
diesel = { version = "2.0", features = ["r2d2", "postgres"] }
dotenv = "0.15"

[profile.release]
opt-level = 3
