[package]
name = "myapp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-async-std","postgres"] }
dotenv = "0.15"