[package]
name = "rust_crud_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
postgres = "0.19"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-rt = "2"
envy = "0.4"
log = "0.4"
env_logger = "0.10"


mime = "0.3.17"
tokio-postgres = "0.7"
