name: my-api
version: 0.1.0.0
flags: {}
extra-deps:
  - postgresql-simple-0.6.4.0
  - aeson-1.5.6.0
  - wai-3.5.8
  - warp-3.3.18
  - http-types-0.12.3
libraries:
  my-api:
    source-dirs: .
executables:
  my-api-exe:
    main: Main.hs
    source-dirs: .
