version: "3"
services:
  web:
    build: .
    environment:
      - PGPASSWORD=Saloon5-Moody-Observing
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=complang
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=Saloon5-Moody-Observing
    ports:
      - "5432:5432"