
name: haskell-crud-api
version: 0.1.0.0
github: "githubuser/haskell-crud-api"
license: MIT
author: "Author Name"
maintainer: "author@example.com"

dependencies:
  - base >= 4.7 && < 5
  - wai
  - warp
  - postgresql-simple
  - aeson
  - servant
  - servant-server

library:
  source-dirs: src

executables:
  haskell-crud-api-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
