
version: '3'
services:
  api:
    build:.
    ports:
      - "8080:8080"
    environment:
      - PGPASSWORD=Saloon5-Moody-Observing
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_DB=complang
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=Saloon5-Moody-Observing
    restart: always
